name: build-dockerx

on:
  push:
    branches: main
    tags:

jobs:
  build-dockerx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker Build (build)
        run: |
          docker build --output "type=image,push=false" -t dockerx:latest .
      -
        name: Login to DockerHub
        if: success() && github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Buildx (push)
        if: success() && github.event_name != 'pull_request'
        run: |
          docker build --output "type=image,push=true" -t dockerx:latest .
